### ISSUE TITLE
Spring/BCryptPasswordEncoder  파일 확장자 관련 

### ISSUE THREAD

**Issue by FeelingXD** [gngsn/TIL#10]
안녕하세요.

Spring/BCryptPasswordEncoder 파일 내용이 markdown 형식으로 작성이 되어있는 것으로 보이나 
repository 에는 확장자가 없이 추적되어 단순 txt형태로 보여지고 있습니다.

**Comment by gngsn** [comment]
확인 감사합니다. 덕분에 수정했습니다 :)
